-- MySQL Script generated by MySQL Workbench
-- Wed Apr  7 09:15:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetom` DEFAULT CHARACTER SET utf8 ;
USE `projetom` ;

-- -----------------------------------------------------
-- Table `projetom`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetom`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetom`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetom`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `numero_cliente` VARCHAR(45) NOT NULL,
  `endereco_cliente` VARCHAR(45) NOT NULL,
  `email_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetom`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetom`.`pedido` (
  `idpedido` INT NULL AUTO_INCREMENT,
  `valor_total` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_pedido_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `projetom`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `projetom`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetom`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetom`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `valor_produto` VARCHAR(45) NOT NULL,
  `descricao_produto` VARCHAR(45) NOT NULL,
  `quantidade_produto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetom`.`pedido_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetom`.`pedido_has_produto` (
  `pedido_idpedido` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`pedido_idpedido`, `produto_idproduto`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_pedido_has_produto_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `projetom`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `projetom`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
